# Uncomment the next line to define a global platform for your project
 platform :ios, '13'

target 'Social Benefit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Social Benefit
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SDWebImageSwiftUI'
  
end
